# Generated by Django 3.0.2 on 2020-02-25 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'business_type',
            },
        ),
        migrations.CreateModel(
            name='PersonalContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contactType', models.CharField(choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Business', 'Business'), ('Colleagues', 'colleagues'), ('Neighbours', 'Neighbours'), ('Acquaintances', 'Acquaintances')], default='Family', max_length=50)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('postalCode', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='CA', max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('emailPersonal', models.EmailField(blank=True, max_length=100)),
                ('emailWork', models.EmailField(blank=True, max_length=100)),
                ('skype', models.CharField(blank=True, max_length=25)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('facebook', models.URLField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('homePhone', models.CharField(blank=True, max_length=25)),
                ('mobilePhone', models.CharField(blank=True, max_length=25)),
                ('workPhone', models.CharField(blank=True, max_length=25)),
                ('workPhoneExt', models.CharField(blank=True, max_length=5)),
                ('spouseFirstName', models.CharField(blank=True, max_length=100)),
                ('spouseLastName', models.CharField(blank=True, max_length=100)),
                ('spouseMiddleName', models.CharField(blank=True, max_length=100)),
                ('spouseEmailPersonal', models.EmailField(blank=True, max_length=100)),
                ('spouseEmailBusiness', models.EmailField(blank=True, max_length=100)),
                ('spouseMobilePhone', models.CharField(blank=True, max_length=25)),
                ('spouseWorkPhone', models.CharField(blank=True, max_length=25)),
                ('spouseworkPhoneExt', models.CharField(blank=True, max_length=5)),
                ('spouseBirthday', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personal_contacts',
                'ordering': ['lastName'],
            },
        ),
        migrations.CreateModel(
            name='ChildContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appContacts.PersonalContact')),
            ],
            options={
                'db_table': 'child_contacts',
            },
        ),
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('businessName', models.CharField(max_length=100)),
                ('contactName', models.CharField(blank=True, max_length=150)),
                ('contactPosition', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('postalCode', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='CA', max_length=100)),
                ('officePhone', models.CharField(blank=True, max_length=25)),
                ('officePhoneExt', models.CharField(blank=True, max_length=10)),
                ('mobilePhone', models.CharField(blank=True, max_length=25)),
                ('tollPhone', models.CharField(blank=True, max_length=25)),
                ('tollPhoneExt', models.CharField(blank=True, max_length=10)),
                ('fax', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('skype', models.CharField(blank=True, max_length=25)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('facebook', models.URLField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('businessType_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appContacts.BusinesType')),
            ],
            options={
                'db_table': 'business_contacts',
                'ordering': ['businessName'],
            },
        ),
    ]
