# Generated by Django 3.0.2 on 2020-02-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscontact',
            old_name='businessType_id',
            new_name='businessType',
        ),
        migrations.RenameField(
            model_name='childcontact',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='personalcontact',
            name='contactType',
            field=models.CharField(choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Business', 'Business'), ('Colleagues', 'Colleagues'), ('Neighbours', 'Neighbours'), ('Acquaintances', 'Acquaintances')], default='Family', max_length=50),
        ),
    ]
