# Generated by Django 3.0.2 on 2020-03-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContacts', '0005_auto_20200322_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontact',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('US', 'Unated States'), ('UA', 'UKraine'), ('RU', 'Russia'), ('DE', 'Germany'), ('FR', 'France'), ('PT', 'Portugal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesscontact',
            name='state',
            field=models.CharField(blank=True, choices=[('ON', 'Ontario'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('NU', 'Nunavut'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('USA', '---USA---'), ('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NA', 'National'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=100),
        ),
    ]
