# Generated by Django 3.0.2 on 2020-03-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContacts', '0006_auto_20200323_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcontact',
            name='country',
            field=models.CharField(blank=True, default='Canada', max_length=100),
        ),
    ]
