# Generated by Django 3.0.2 on 2020-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContacts', '0008_auto_20200323_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontact',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('US', 'Unated States'), ('UA', 'Ukraine'), ('RU', 'Russia'), ('DE', 'Germany'), ('FR', 'France'), ('PT', 'Portugal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalcontact',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('US', 'Unated States'), ('UA', 'Ukraine'), ('RU', 'Russia'), ('DE', 'Germany'), ('FR', 'France'), ('PT', 'Portugal')], max_length=50, null=True),
        ),
    ]
