# Generated by Django 3.0.2 on 2020-03-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContacts', '0010_auto_20200323_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryCode',
        ),
        migrations.AlterField(
            model_name='personalcontact',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('US', 'Unated States'), ('UA', 'Ukraine'), ('RU', 'Russia'), ('DE', 'Germany'), ('FR', 'France'), ('PT', 'Portugal')], default='Ontario', max_length=50, null=True),
        ),
    ]
