# Generated by Django 3.0.2 on 2020-03-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContacts', '0013_auto_20200329_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontact',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businesscontact',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalcontact',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalcontact',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
