# Generated by Django 3.0.2 on 2020-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContacts', '0015_auto_20200408_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontact',
            name='country',
            field=models.CharField(blank=True, choices=[('CA', 'Canada'), ('US', 'United States'), ('UA', 'Ukraine'), ('RU', 'Russia'), ('DE', 'Germany'), ('FR', 'France'), ('PT', 'Portugal'), ('AE', 'United Arab Emirates'), ('IL', 'Israel'), ('PL', 'Poland')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalcontact',
            name='country',
            field=models.CharField(blank=True, choices=[('CA', 'Canada'), ('US', 'United States'), ('UA', 'Ukraine'), ('RU', 'Russia'), ('DE', 'Germany'), ('FR', 'France'), ('PT', 'Portugal'), ('AE', 'United Arab Emirates'), ('IL', 'Israel'), ('PL', 'Poland')], default='Canada', max_length=50),
        ),
    ]
