# Generated by Django 3.0.2 on 2020-05-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContacts', '0016_auto_20200411_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='personalcontact',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='personalcontact',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
