# Generated by Django 3.0.2 on 2020-04-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='timeZone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
