# Generated by Django 3.0.2 on 2020-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeather', '0002_auto_20200419_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='seq',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
