# Generated by Django 3.0.2 on 2020-04-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeather', '0003_location_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
